#!/bin/sh

SELF=$0
CMD=$1
if [ $# -gt 0 ]; then
	shift
fi

case $CMD in
	'')
		ROOTFS=`cd "${SELF%/*}"; pwd`

		if [ "$ROOTFS" = "" ] || [ "$ROOTFS" = "/home/andbot/bin" ]; then
			echo "usage: $SELF <command> [<argument>, ...]"
			echo "commands:"
			echo "	init:		repo init"
			echo "	sync:		repo sync"
			echo "	vendor:		prepare vendor files"
			echo "	brunch:		build"
			echo "	mka:		build (i.e.: andbot mka bacon)"
			echo "	make:		build (i.e.: andbot make -j[#cpus] bacon)"
			echo "	manifest:	fetch local_manifest.xml"
			echo "	github-https:	workaround for github-related errors"
			echo "	github-git:	undo aforementioned workaround"
			echo "	release-512:	workaround for java-related memory errors"
			echo "	release-2048:	undo aforementioned workaround"
			exit
		fi

		if [ $(id -u) -ne 0 ]; then
			sudo $SELF
			exit
		fi

		mount | grep -Fq "$ROOTFS/proc"
		MOUNTED=$?
		if [ $MOUNTED -ne 0 ]; then
			echo Mounting /proc, /sys, /dev, and /dev/pts
			mount -o bind /proc "$ROOTFS/proc"
			mount -o bind /sys "$ROOTFS/sys"
			mount -o bind /dev "$ROOTFS/dev"
			mount -o bind /dev/pts "$ROOTFS/dev/pts"
		fi

		chown -R 0:0 "$ROOTFS/usr/bin/sudo" "$ROOTFS/etc/sudoers" "$ROOTFS/etc/sudoers.d"
		chmod 4755 "$ROOTFS/usr/bin/sudo"
		HOME=$ROOTFS/home/andbot PATH=$ROOTFS/home/andbot/android/system/out/host/linux-x86/bin:$ROOTFS/home/andbot/bin adb root
		echo Welcome to AndBot
		chroot "$ROOTFS" su andbot -c 'cd ~/android/system; USE_CCACHE=1 bash -l'

		if [ $MOUNTED -ne 0 ]; then
			echo Unmounting /proc, /sys, /dev, and /dev/pts
			while umount -l "$ROOTFS/dev/pts" 2> /dev/null; do true; done
			while umount -l "$ROOTFS/dev" 2> /dev/null; do true; done
			while umount -l "$ROOTFS/sys" 2> /dev/null; do true; done
			while umount -l "$ROOTFS/proc" 2> /dev/null; do true; done
		fi
		;;
	'init')
		set -e -x
		cd ~/android/system
		repo init -u git://github.com/CyanogenMod/android.git -b ics $@
		;;
	'sync')
		set -e -x
		cd ~/android/system
		repo sync $@
		cd ~/android/system/system/vold
		git fetch http://review.cyanogenmod.com/p/CyanogenMod/android_system_vold refs/changes/77/11277/1 && git cherry-pick FETCH_HEAD
		cd ~/android/system/external/mesa3d/src/glsl
		if ! grep -q '<stddef.h>' linker.cpp; then
			sed -i '1i #include <stddef.h>' linker.cpp
		fi
		;;
	'vendor')
		set -e -x
		cd ~/android/system/device/bn/encore
		./extract-files.sh
		cd ~/android/system/vendor/cm
		./get-prebuilts
		;;
	'alternative-vendor-i-have-a-nook-color')
		set -e -x
		curl http://dl.dropbox.com/u/1213413/cm9/encore.tgz > ~/android/encore.tgz
		mkdir -p ~/android/system/vendor/bn/encore/proprietary
		tar pzxvf ~/android/encore.tgz -C ~/android/system/vendor/bn/encore/
		rm ~/android/encore.tgz
		cd ~/android/system/device/bn/encore
		./setup-makefiles.sh
		cd ~/android/system/vendor/cm
		./get-prebuilts
		;;
	'brunch')
		set -e -x
		cd ~/android/system
		USE_CCACHE=1 bash -c ". build/envsetup.sh; lunch cm_encore-userdebug; brunch $@"
		rm -f update-cm-9.0.0-RC0-NookColor-KANG-signed.zip
		ln out/target/product/encore/update-cm-9.0.0-RC0-NookColor-KANG-signed.zip ./
		;;
	'mka')
		set -e -x
		cd ~/android/system
		USE_CCACHE=1 bash -c ". build/envsetup.sh; lunch cm_encore-userdebug; mka $@"
		rm -f update-cm-9.0.0-RC0-NookColor-KANG-signed.zip
		ln out/target/product/encore/update-cm-9.0.0-RC0-NookColor-KANG-signed.zip ./
		;;
	'make')
		set -e -x
		cd ~/android/system
		USE_CCACHE=1 bash -c ". build/envsetup.sh; lunch cm_encore-userdebug; make $@"
		rm -f update-cm-9.0.0-RC0-NookColor-KANG-signed.zip
		ln out/target/product/encore/update-cm-9.0.0-RC0-NookColor-KANG-signed.zip ./
		;;
	'manifest')
		set -e -x
		curl http://pastebin.com/raw.php?i=FrFJmVtJ > ~/android/system/.repo/local_manifest.xml
		;;
	'github-https')
		set -e -x
		sed 's/git\:\/\/github.com/https\:\/\/github.com/' ~/android/system/.repo/manifest.xml > .manifest.xml
		mv .manifest.xml ~/android/system/.repo/manifest.xml
		;;
	'github-git')
		set -e -x
		sed 's/https\:\/\/github.com/git\:\/\/github.com/' ~/android/system/.repo/manifest.xml > .manifest.xml
		mv .manifest.xml ~/android/system/.repo/manifest.xml
		;;
	'release-512')
		set -e -x
		sed 's/-Xmx2048m/-Xmx512m/' ~/android/system/build/tools/releasetools/common.py > .common.py
		mv .common.py ~/android/system/build/tools/releasetools/common.py
		;;
	'release-2048')
		set -e -x
		sed 's/-Xmx512m/-Xmx2048m/' ~/android/system/build/tools/releasetools/common.py > .common.py
		mv .common.py ~/android/system/build/tools/releasetools/common.py
		;;
esac
